kafka:
  pool: nav-dev
sqlInstances:
  diskAutoresize: false
  pointInTimeRecovery: false
cluster: dev-gcp
tenant: trygdeetaten.no
ROLE_SAKSBEHANDLER: 1b3a2c4d-d620-4fcf-a29b-a6cdadf29680
ROLE_FORTROLIG: ea930b6b-9397-44d9-b9e6-f4cf527a632a
ROLE_STRENGT_FORTROLIG: 5ef775f2-61f8-4283-bf3d-8d03f428aa14
ROLE_SKJERMING: dbe4ad45-320b-4e9a-aaa1-73cca4ee124d
